#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-IO-Tee
Version  : 0.66
Release  : 28
URL      : https://cpan.metacpan.org/authors/id/N/NE/NEILB/IO-Tee-0.66.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/N/NE/NEILB/IO-Tee-0.66.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libi/libio-tee-perl/libio-tee-perl_0.65-1.debian.tar.xz
Summary  : 'Multiplex output to multiple output handles'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-IO-Tee-license = %{version}-%{release}
Requires: perl-IO-Tee-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
Perl 5 module IO::Tee
Lingua::Stem::Ru is a pure perl module that lets you multiplex output
to multiple file handles.

%package dev
Summary: dev components for the perl-IO-Tee package.
Group: Development
Provides: perl-IO-Tee-devel = %{version}-%{release}
Requires: perl-IO-Tee = %{version}-%{release}

%description dev
dev components for the perl-IO-Tee package.


%package license
Summary: license components for the perl-IO-Tee package.
Group: Default

%description license
license components for the perl-IO-Tee package.


%package perl
Summary: perl components for the perl-IO-Tee package.
Group: Default
Requires: perl-IO-Tee = %{version}-%{release}

%description perl
perl components for the perl-IO-Tee package.


%prep
%setup -q -n IO-Tee-0.66
cd %{_builddir}
tar xf %{_sourcedir}/libio-tee-perl_0.65-1.debian.tar.xz
cd %{_builddir}/IO-Tee-0.66
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/IO-Tee-0.66/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-IO-Tee
cp %{_builddir}/IO-Tee-0.66/LICENSE %{buildroot}/usr/share/package-licenses/perl-IO-Tee/943d005049c7cef6b1c9f0a1ba3e880ccee12abb
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-IO-Tee/971799ba6d9df1bad73c9d4d42abd781a891f1f6
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/IO::Tee.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-IO-Tee/943d005049c7cef6b1c9f0a1ba3e880ccee12abb
/usr/share/package-licenses/perl-IO-Tee/971799ba6d9df1bad73c9d4d42abd781a891f1f6

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
